---
title: "eds212_day2_activities"
---

## Activities day 2!

```{r}
library(tidyverse)
library(palmerpenguins)
```

A. find the slope of f(x) = x\^2 at x = 3

B. find the slope of P(a) = 2(3a + 2)\^4 - 5 at a = 1.2

```{r}

#A

fx <- expression(x^2)
x <- 2
D(fx, 'x')
```

```{r}
pa <- expression(2 * ((3 * a + 2)^4) - 5)
a <- 1.2
D(pa, 'a')
```

## Section 4

```{r}
ggplot() +
  geom_point(data = penguins, 
             aes(x = bill_length_mm, 
                 y = bill_depth_mm,
                 color = species)
             )
```

```{r}
ggplot() +
  geom_jitter(data = penguins, 
              aes(x = species,
                  y = flipper_length_mm,
                  color = island)) +
  labs(title = "Penguin flipper length by species",
       x = "Species",
       y = "Flipper length (mm)",
       color = "Island") +
#  scale_shape_manual() +
  theme_minimal()
```

```{r}
ggplot() +
  geom_jitter(data = penguins, 
              aes(x = species,
                  y = flipper_length_mm,
                  color = island,
                  shape = island)) +
  labs(title = "Penguin flipper length by species",
       x = "Species",
       y = "Flipper length (mm)"
    #   ,color = "Island"
       ) +
#  scale_shape_manual() +
  theme_minimal()
```
